version: '3'
services:
  node1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:latest
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
  node2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:latest
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    volumes:
      - /var/lib/mysql2:/var/lib/mysql
      
  node3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:latest
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    volumes:
      - /var/lib/mysql3:/var/lib/mysql
      
  mysqlshell:
    env_file:
      - mysqlshell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - node1
      - node2
      - node3
      
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:latest
    ports:
      - "6446:6446"
    depends_on:
      - node1
      - node2
      - node3
      - mysqlshell
    restart: on-failure
    
  dbwebapp:
    env_file:
      - dbwebapp.env
    image: neumayer/dbwebapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql-router
      
  webserve:
    env_file:
      - mysqlshell.env
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    depends_on:
      - mysql-router
